# Generated by Django 4.1.3 on 2022-11-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profil_pics',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
