# Generated by Django 4.1.3 on 2022-11-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_profil_pics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profil_pics',
            new_name='profile_pic',
        ),
    ]
